[workspace]

members = [
    "cmd",
    "config/agent-rest",
    "server/agent-rest",
    "infrastructure",
    "domain",
    "data/cache",
    "data/database",
    "data/queue",
    "data/search",
]

[profile.dev]
debug = true

[profile.release]
debug = false

[profile.bench]
debug = false
